apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.12

patches:
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
    patch: |-
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
      data:
        policy.default: role:admin
