# permissions for end users to edit analysisruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: analysisrun-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multi-cluster-rollouts
    app.kubernetes.io/part-of: multi-cluster-rollouts
    app.kubernetes.io/managed-by: kustomize
  name: analysisrun-editor-role
rules:
- apiGroups:
  - rollouts.example.com
  resources:
  - analysisruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollouts.example.com
  resources:
  - analysisruns/status
  verbs:
  - get
