# permissions for end users to view placements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: placement-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multi-cluster-rollouts
    app.kubernetes.io/part-of: multi-cluster-rollouts
    app.kubernetes.io/managed-by: kustomize
  name: placement-viewer-role
rules:
- apiGroups:
  - rollouts.example.com
  resources:
  - placements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollouts.example.com
  resources:
  - placements/status
  verbs:
  - get
