apiVersion: rollouts.example.com/v1alpha1
kind: AnalysisTemplate
metadata:
  name: example-ready-analysis
spec:
  metric:
    successCondition: result[0] > 0
    provider:
      prometheus:
        address: http://thanos-query.172.18.0.2.nip.io/
        query: |
          count(kube_deployment_status_replicas_ready{namespace="argocd-test-multi-cluster-ingress"}) > 2
