apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-application
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-example-application'
    spec:
      destination:
        name: '{{name}}'
        namespace: example-application
      project: example-project
      source:
        repoURL: https://github.com/david-martin/argocd-test-app.git
        targetRevision: main
        path: argocd-test-ingress-ignoredifferences
      syncPolicy:
        syncOptions:
        - CreateNamespace=true