apiVersion: rollouts.example.com/v1alpha1
kind: AnalysisRun
metadata:
  labels:
    app.kubernetes.io/name: analysisrun
    app.kubernetes.io/instance: analysisrun-sample
    app.kubernetes.io/part-of: multi-cluster-rollouts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: multi-cluster-rollouts
  name: analysisrun-sample
spec:
  # TODO(user): Add fields here
